# Generated by Django 3.2 on 2021-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('text', models.TextField(verbose_name='Main text')),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
