# Generated by Django 3.2 on 2021-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210613_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
