# Generated by Django 3.2 on 2021-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='Main/static/images/', verbose_name='Изображение'),
        ),
    ]
