# Generated by Django 3.2 on 2021-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Заголовок статьи')),
                ('description', models.TextField(verbose_name='Описание статьи')),
                ('content', models.TextField(verbose_name='Статья')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
