# Generated by Django 3.2 on 2021-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('second_name', models.TextField(verbose_name='Фамилия')),
                ('position', models.TextField(verbose_name='Должность')),
                ('date', models.TextField(verbose_name='Date')),
                ('title', models.TextField(verbose_name='Заголовок публикации')),
                ('content', models.TextField(verbose_name='Публикация')),
            ],
        ),
    ]
