# Generated by Django 3.2 on 2021-06-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date',
        ),
    ]
